### ISSUE TITLE
npm link problem

### ISSUE THREAD

**Issue by jmls** [Backbase/filesystem-bower-resolver#2]
I'm using npm link to install modules into other projects whilst they are under development

npm link myModule creates a link to the folder where the module is being developed, so there isn't a folder in node_modules per se

``` html
ls -l node_modules/myModule

lrwxrwxrwx 1 root root 75 Sep 22 14:41 ./node_modules/myModule -> /workspace/.npm/lib/node_modules/myModule
```

unfortunately, it looks like the resolver doesn't handle links, as when I put 

``` html
"myModule": "./node_modules/myModule" 
```

into bower.json, I get a 

``` html
bower ENOTFOUND Package myModule=./node_modules/myModule not found
```

**Comment by igord** [comment]
which version of resolver are you using? it works fine for me with symlinks
